# Generated by Django 3.2.8 on 2021-10-22 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='tuning date')),
                ('tune', models.CharField(choices=[('S', 'Standard'), ('D', 'Drop D'), ('C', 'Drop C'), ('G', 'Open G')], default='S', max_length=1)),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.guitar')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
