# Generated by Django 3.2.8 on 2021-10-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tuning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuning',
            name='tune',
            field=models.CharField(choices=[('S', 'Standard'), ('D', 'Drop D'), ('C', 'Drop C'), ('G', 'Open G')], default='S', max_length=1),
        ),
    ]
